# Generated by Django 2.1.5 on 2019-12-17 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='criticalvoltageevent',
            name='phase_a',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='criticalvoltageevent',
            name='phase_b',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='criticalvoltageevent',
            name='phase_c',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='phasedropevent',
            name='phase_a',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='phasedropevent',
            name='phase_b',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='phasedropevent',
            name='phase_c',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='precariousvoltageevent',
            name='phase_a',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='precariousvoltageevent',
            name='phase_b',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='precariousvoltageevent',
            name='phase_c',
            field=models.FloatField(default=0),
        ),
    ]
