# Generated by Django 2.1.5 on 2020-01-08 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('transductor', '0001_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FailedConnectionEvent',
            new_name='FailedConnectionTransductorEvent',
        ),
    ]
