# Generated by Django 2.1.5 on 2020-01-13 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20200108_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
