# Generated by Django 2.1.5 on 2020-01-20 16:05

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_ended_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voltagerelatedevent',
            name='measures',
        ),
        migrations.AddField(
            model_name='event',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
            preserve_default=False,
        ),
    ]
