# Generated by Django 3.0.2 on 2020-01-22 12:37

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20200120_1605'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voltagerelatedevent',
            options={'base_manager_name': 'non_polymorphic'},
        ),
        migrations.AlterModelManagers(
            name='criticalvoltageevent',
            managers=[
                ('non_polymorphic', django.db.models.manager.Manager()),
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='phasedropevent',
            managers=[
                ('non_polymorphic', django.db.models.manager.Manager()),
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='precariousvoltageevent',
            managers=[
                ('non_polymorphic', django.db.models.manager.Manager()),
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='voltagerelatedevent',
            managers=[
                ('non_polymorphic', django.db.models.manager.Manager()),
            ],
        ),
    ]
