# Generated by Django 3.0.2 on 2020-01-22 15:32

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20200122_1237'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoltageEventDebouncer',
            fields=[
                ('voltagerelatedevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.VoltageRelatedEvent')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('events.voltagerelatedevent',),
            managers=[
                ('non_polymorphic', django.db.models.manager.Manager()),
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
