stages:
- name: Publish image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: smi-slave:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: registry.lappis.rocks

- name: Deploy Staging
  when:
    branch: development
  steps:
  - applyYamlConfig:
      path: ./deploy/staging/deployment-slave.yaml

- name: Deploy Production
  when:
    branch: master
  steps:
  - applyYamlConfig:
      path: ./deploy/production/deployment-slave.yaml


branch:
  include: [ development, master ]
notification: {}
