version: "3.9"

services:
    slave-db:
        container_name: slave-db
        restart: unless-stopped
        image: postgres:15.2-bullseye
        env_file: dev-env
        volumes:
            - ./.docker/pgdata:/var/lib/postgresql/data
        networks:
            - slave-network

    slave-api:
        container_name: slave-api
        restart: unless-stopped
        pull_policy: never
        env_file: dev-env
        command: ["sh", "scripts/start-dev.sh"]
        image: ${IMAGE_NAME:-slave-api}:${IMAGE_TAG:-development}
        build:
            context: .
            dockerfile: Dockerfile
            args:
                API_KEY: ${API_KEY_CRONITOR}
        ports:
            - 8000:8000
        networks:
            - slave-network
            - sige-network
        volumes:
            - .:/sige-master
            - ./.docker/zsh/powerlevel10k/.p10k.zsh:/home/python/.p10k.zsh:delegated
            - ./.docker/zsh/history:/home/python/zsh:delegated
        depends_on:
            - slave-db

volumes:
    pg-data:
        name: slave-pgdata
    pip_cache:
        name: slave-pip-cache

networks:
    slave-network:
        name: slave-network
    sige-network:
        driver: bridge
        name: sige-network
