# Generated by Django 3.2.18 on 2023-05-01 03:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_collector', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transductor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('serial_number', models.CharField(max_length=8, unique=True)),
                ('ip_address', models.GenericIPAddressField(protocol='IPv4', unique=True)),
                ('port', models.PositiveIntegerField()),
                ('model', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('broken', models.BooleanField(default=False)),
                ('firmware_version', models.CharField(max_length=20)),
                ('installation_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('physical_location', models.CharField(default='', max_length=30)),
                ('quarterly_data_rescued', models.BooleanField(default=False)),
                ('monthly_data_rescued', models.BooleanField(default=False)),
                ('geolocation_longitude', models.DecimalField(decimal_places=10, max_digits=15)),
                ('geolocation_latitude', models.DecimalField(decimal_places=10, max_digits=15)),
                ('last_clock_battery_change', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('memory_map', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='data_collector.memorymap')),
            ],
        ),
        migrations.CreateModel(
            name='TimeInterval',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('begin', models.DateTimeField()),
                ('end', models.DateTimeField(null=True)),
                ('transductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeintervals', to='transductor.transductor')),
            ],
        ),
        migrations.CreateModel(
            name='TransductorVoltageState',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('current_voltage_state', models.CharField(choices=[('CriticalHigh', 'CriticalHigh'), ('PrecariousHigh', 'PrecariousHigh'), ('Normal', 'Normal'), ('PrecariousLow', 'PrecariousLow'), ('CriticalLow', 'CriticalLow'), ('PhaseDown', 'PhaseDown')], default='Normal', max_length=14)),
                ('phase', models.CharField(choices=[('voltage_a', 'voltage_a'), ('voltage_b', 'voltage_b'), ('voltage_c', 'voltage_c')], max_length=9)),
                ('transductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voltage_phase_states', to='transductor.transductor')),
            ],
            options={
                'unique_together': {('transductor', 'phase')},
            },
        ),
    ]
