# Generated by Django 3.0.2 on 2020-03-09 12:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyTransductor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=8, unique=True)),
                ('ip_address', models.CharField(default='0.0.0.0', max_length=15, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_ip_address', message='Incorrect IP address format', regex='^(?:[0-9]{1,3}\\.){3}[0-9]{1,3}$')])),
                ('port', models.IntegerField(default=1001)),
                ('model', models.CharField(default='EnergyTransductorModel', max_length=50)),
                ('broken', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('firmware_version', models.CharField(max_length=20)),
                ('installation_date', models.DateTimeField(blank=True, null=True)),
                ('physical_location', models.CharField(default='', max_length=30)),
                ('geolocation_longitude', models.DecimalField(decimal_places=10, max_digits=15)),
                ('geolocation_latitude', models.DecimalField(decimal_places=10, max_digits=15)),
                ('last_clock_battery_change', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TimeInterval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin', models.DateTimeField()),
                ('end', models.DateTimeField(null=True)),
                ('transductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeintervals', to='transductor.EnergyTransductor')),
            ],
        ),
    ]
