# Generated by Django 2.1.5 on 2019-11-19 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transductor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeInterval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin', models.DateTimeField()),
                ('end', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='energytransductor',
            name='last_collection',
        ),
        migrations.AddField(
            model_name='timeinterval',
            name='transductor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeintervals', to='transductor.EnergyTransductor'),
        ),
    ]
