# Generated by Django 2.1.5 on 2019-01-29 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transductor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energytransductor',
            name='serial_number',
            field=models.CharField(max_length=8, primary_key=True, serialize=False, unique=True),
        ),
    ]
