# Generated by Django 3.0.2 on 2020-04-09 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transductor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='energytransductor',
            name='monthly_data_rescued',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='energytransductor',
            name='quarterly_data_rescued',
            field=models.BooleanField(default=False),
        ),
    ]
