# Generated by Django 3.2.18 on 2023-05-01 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transductor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeinterval',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='transductor',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='transductorvoltagestate',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
