# Generated by Django 2.1.5 on 2019-02-04 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transductor', '0002_auto_20190129_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='energytransductor',
            name='firmware_version',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='energytransductor',
            name='geolocation_latitude',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='energytransductor',
            name='geolocation_longitude',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='energytransductor',
            name='installation_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='energytransductor',
            name='last_clock_battery_change',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='energytransductor',
            name='physical_location',
            field=models.CharField(default='', max_length=30),
        ),
    ]
