# Generated by Django 3.0.14 on 2021-05-16 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transductor', '0002_auto_20200409_1119'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransductorVoltageState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_voltage_state', models.CharField(choices=[('CriticalHigh', 'CriticalHigh'), ('PrecariousHigh', 'PrecariousHigh'), ('Normal', 'Normal'), ('PrecariousLow', 'PrecariousLow'), ('CriticalLow', 'CriticalLow'), ('PhaseDown', 'PhaseDown')], default='Normal', max_length=14)),
                ('phase', models.CharField(choices=[('voltage_a', 'voltage_a'), ('voltage_b', 'voltage_b'), ('voltage_c', 'voltage_c')], max_length=9)),
                ('transductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voltage_phase_states', to='transductor.EnergyTransductor')),
            ],
            options={
                'unique_together': {('transductor', 'phase')},
            },
        ),
    ]
