# Generated by Django 2.1.5 on 2019-11-19 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transductor', '0002_auto_20191119_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeinterval',
            name='end',
            field=models.DateTimeField(null=True),
        ),
    ]
