# Generated by Django 3.2.18 on 2023-05-01 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transductor', '0002_auto_20230501_0358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeinterval',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transductor',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transductorvoltagestate',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
