# Generated by Django 2.1.5 on 2019-06-04 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transductor', '0003_auto_20190204_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energytransductor',
            name='firmware_version',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='energytransductor',
            name='geolocation_latitude',
            field=models.DecimalField(decimal_places=10, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='energytransductor',
            name='geolocation_longitude',
            field=models.DecimalField(decimal_places=10, max_digits=15, null=True),
        ),
    ]
