# Generated by Django 2.1.5 on 2019-06-10 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transductor', '0003_auto_20190204_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='energytransductor',
            name='last_collection',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
