# Generated by Django 2.1.5 on 2020-01-15 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transductor', '0003_auto_20191119_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='energytransductor',
            name='monthly_data_rescued',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='energytransductor',
            name='quarterly_data_rescued',
            field=models.BooleanField(default=False),
        ),
    ]
