# Generated by Django 2.1.5 on 2019-06-24 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transductor', '0003_auto_20190204_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energytransductor',
            name='model',
            field=models.ForeignKey(db_column='model_code', on_delete=django.db.models.deletion.DO_NOTHING, to='transductor_model.TransductorModel'),
        ),
    ]
