# Generated by Django 2.1.5 on 2019-02-12 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transductor', '0003_auto_20190204_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='energytransductor',
            name='firmware_version',
        ),
    ]
