# Generated by Django 3.0.2 on 2020-01-22 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transductor', '0003_auto_20191119_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='energytransductor',
            name='port',
            field=models.IntegerField(default=1001),
        ),
    ]
