# Generated by Django 2.1.5 on 2019-09-16 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transductor', '0004_auto_20190624_1204'),
        ('transductor', '0004_energytransductor_last_collection'),
    ]

    operations = [
    ]
