# Generated by Django 3.0.2 on 2020-03-04 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transductor', '0004_auto_20200115_2305'),
        ('transductor', '0004_energytransductor_port'),
    ]

    operations = [
    ]
