# Generated by Django 2.1.5 on 2019-08-13 15:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('transductor', '0012_auto_20190717_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energytransductor',
            name='installation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 13, 18, 33, 38, 116818, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='energytransductor',
            name='last_clock_battery_change',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 13, 18, 33, 38, 116914, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='energytransductor',
            name='last_collection',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 13, 18, 33, 38, 116721, tzinfo=utc)),
        ),
    ]
