# Generated by Django 2.1.5 on 2019-08-19 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transductor', '0004_auto_20190624_1204'),
        ('transductor', '0021_auto_20190815_1056'),
    ]

    operations = [
    ]
