# Generated by Django 3.2.18 on 2023-05-01 03:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryMap',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('model_transductor', models.CharField(max_length=30)),
                ('minutely', models.JSONField()),
                ('quarterly', models.JSONField()),
                ('monthly', models.JSONField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Memory Maps',
            },
        ),
    ]
