# Generated by Django 3.2.18 on 2023-05-01 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_collector', '0002_alter_memorymap_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memorymap',
            name='model_transductor',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
