---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: smi-slave-staging
  labels: 
    app: postgres
spec:
  ports:
    - port: 5432
  selector:
    app: postgres
    tier: database
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: smi-slave-staging
  labels:
    app: postgres
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: postgres
      tier: database
  template:
    metadata:
      name: postgres
      labels:
        app: postgres
        tier: database
    spec:
      volumes:
      - name: postgres-pv
        persistentVolumeClaim:
          claimName: postgres-staging-pvc
      containers:
      - name: postgres
        image: postgres:9.6-alpine
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: "slave-staging-secrets"
              key: "db-user"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: "slave-staging-secrets"
              key: "db-user-pass"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_DB
          value: "smi-slave-dev"
        ports:
        - containerPort: 5432
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-staging-pvc
  namespace: smi-slave-staging
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
