# Generated by Django 2.1.5 on 2019-02-06 15:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transductor_model', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transductormodel',
            old_name='register_addresses',
            new_name='minutely_register_addresses',
        ),
        migrations.AddField(
            model_name='transductormodel',
            name='monthly_register_addresses',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None), default=[], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transductormodel',
            name='quarterly_register_addresses',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None), default=[], size=None),
            preserve_default=False,
        ),
    ]
