# Generated by Django 2.1.5 on 2019-09-23 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transductor_model', '0002_auto_20190206_1352'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TransductorModel',
        ),
    ]
