# Generated by Django 2.1.5 on 2019-06-04 11:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transductor_model', '0002_auto_20190206_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transductormodel',
            name='minutely_register_addresses',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None), default=None, size=None),
        ),
        migrations.AlterField(
            model_name='transductormodel',
            name='monthly_register_addresses',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None), default=None, size=None),
        ),
        migrations.AlterField(
            model_name='transductormodel',
            name='quarterly_register_addresses',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None), default=None, size=None),
        ),
    ]
