# Generated by Django 2.1.5 on 2019-01-23 14:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyMeasurement',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID'
                    )
                ),
                (
                    'collection_date',
                    models.DateTimeField(
                        default=datetime.datetime.now
                    )
                ),
                ('frequency_a', models.FloatField(default=None)),
                ('voltage_a', models.FloatField(default=None)),
                ('voltage_b', models.FloatField(default=None)),
                ('voltage_c', models.FloatField(default=None)),
                ('current_a', models.FloatField(default=None)),
                ('current_b', models.FloatField(default=None)),
                ('current_c', models.FloatField(default=None)),
                ('active_power_a', models.FloatField(default=None)),
                ('active_power_b', models.FloatField(default=None)),
                ('active_power_c', models.FloatField(default=None)),
                ('total_active_power', models.FloatField(default=None)),
                ('reactive_power_a', models.FloatField(default=None)),
                ('reactive_power_b', models.FloatField(default=None)),
                ('reactive_power_c', models.FloatField(default=None)),
                ('total_reactive_power', models.FloatField(default=None)),
                ('apparent_power_a', models.FloatField(default=None)),
                ('apparent_power_b', models.FloatField(default=None)),
                ('apparent_power_c', models.FloatField(default=None)),
                ('total_apparent_power', models.FloatField(default=None)),
                ('power_factor_a', models.FloatField(default=None)),
                ('power_factor_b', models.FloatField(default=None)),
                ('power_factor_c', models.FloatField(default=None)),
                ('total_power_factor', models.FloatField(default=None)),
                ('dht_voltage_a', models.FloatField(default=None)),
                ('dht_voltage_b', models.FloatField(default=None)),
                ('dht_voltage_c', models.FloatField(default=None)),
                ('dht_current_a', models.FloatField(default=None)),
                ('dht_current_b', models.FloatField(default=None)),
                ('dht_current_c', models.FloatField(default=None)),
                ('consumption_a', models.FloatField(default=None)),
                ('consumption_b', models.FloatField(default=None)),
                ('consumption_c', models.FloatField(default=None)),
                ('total_consumption', models.FloatField(default=None)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
