# Generated by Django 3.0.2 on 2020-03-09 12:18

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transductor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuarterlyMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slave_collection_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('transductor_collection_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('generated_energy_peak_time', models.FloatField(default=0)),
                ('generated_energy_off_peak_time', models.FloatField(default=0)),
                ('consumption_peak_time', models.FloatField(default=0)),
                ('consumption_off_peak_time', models.FloatField(default=0)),
                ('inductive_power_peak_time', models.FloatField(default=0)),
                ('inductive_power_off_peak_time', models.FloatField(default=0)),
                ('capacitive_power_peak_time', models.FloatField(default=0)),
                ('capacitive_power_off_peak_time', models.FloatField(default=0)),
                ('transductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurement_quarterlymeasurement', to='transductor.EnergyTransductor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MonthlyMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slave_collection_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('transductor_collection_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('generated_energy_peak_time', models.FloatField(default=0)),
                ('generated_energy_off_peak_time', models.FloatField(default=0)),
                ('consumption_peak_time', models.FloatField(default=0)),
                ('consumption_off_peak_time', models.FloatField(default=0)),
                ('inductive_power_peak_time', models.FloatField(default=0)),
                ('inductive_power_off_peak_time', models.FloatField(default=0)),
                ('capacitive_power_peak_time', models.FloatField(default=0)),
                ('capacitive_power_off_peak_time', models.FloatField(default=0)),
                ('active_max_power_peak_time', models.FloatField(default=0)),
                ('active_max_power_off_peak_time', models.FloatField(default=0)),
                ('reactive_max_power_peak_time', models.FloatField(default=0)),
                ('reactive_max_power_off_peak_time', models.FloatField(default=0)),
                ('active_max_power_list_peak', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=None, size=None)),
                ('active_max_power_list_peak_time', django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(), default=None, size=None)),
                ('active_max_power_list_off_peak', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=None, size=None)),
                ('active_max_power_list_off_peak_time', django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(), default=None, size=None)),
                ('reactive_max_power_list_peak', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=None, size=None)),
                ('reactive_max_power_list_peak_time', django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(), default=None, size=None)),
                ('reactive_max_power_list_off_peak', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=None, size=None)),
                ('reactive_max_power_list_off_peak_time', django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(), default=None, size=None)),
                ('transductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurement_monthlymeasurement', to='transductor.EnergyTransductor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MinutelyMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slave_collection_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('transductor_collection_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('frequency_a', models.FloatField(default=0)),
                ('voltage_a', models.FloatField(default=0)),
                ('voltage_b', models.FloatField(default=0)),
                ('voltage_c', models.FloatField(default=0)),
                ('current_a', models.FloatField(default=0)),
                ('current_b', models.FloatField(default=0)),
                ('current_c', models.FloatField(default=0)),
                ('active_power_a', models.FloatField(default=0)),
                ('active_power_b', models.FloatField(default=0)),
                ('active_power_c', models.FloatField(default=0)),
                ('total_active_power', models.FloatField(default=0)),
                ('reactive_power_a', models.FloatField(default=0)),
                ('reactive_power_b', models.FloatField(default=0)),
                ('reactive_power_c', models.FloatField(default=0)),
                ('total_reactive_power', models.FloatField(default=0)),
                ('apparent_power_a', models.FloatField(default=0)),
                ('apparent_power_b', models.FloatField(default=0)),
                ('apparent_power_c', models.FloatField(default=0)),
                ('total_apparent_power', models.FloatField(default=0)),
                ('power_factor_a', models.FloatField(default=0)),
                ('power_factor_b', models.FloatField(default=0)),
                ('power_factor_c', models.FloatField(default=0)),
                ('total_power_factor', models.FloatField(default=0)),
                ('dht_voltage_a', models.FloatField(default=0)),
                ('dht_voltage_b', models.FloatField(default=0)),
                ('dht_voltage_c', models.FloatField(default=0)),
                ('dht_current_a', models.FloatField(default=0)),
                ('dht_current_b', models.FloatField(default=0)),
                ('dht_current_c', models.FloatField(default=0)),
                ('transductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurement_minutelymeasurement', to='transductor.EnergyTransductor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
