# Generated by Django 2.1.5 on 2020-01-14 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlymeasurement',
            name='active_max_power_list_off_peak_time',
        ),
        migrations.RemoveField(
            model_name='monthlymeasurement',
            name='active_max_power_list_peak_time',
        ),
        migrations.RemoveField(
            model_name='monthlymeasurement',
            name='reactive_max_power_list_off_peak_time',
        ),
        migrations.RemoveField(
            model_name='monthlymeasurement',
            name='reactive_max_power_list_peak_time',
        ),
    ]
