# Generated by Django 2.1.5 on 2019-01-23 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transductor', '0001_initial'),
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='energymeasurement',
            name='transductor',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='transductor.EnergyTransductor'
            ),
        ),
    ]
