# Generated by Django 3.2.18 on 2023-05-01 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0002_auto_20230501_0358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minutelymeasurement',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='monthlymeasurement',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='quarterlymeasurement',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='referencemeasurement',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
