# Generated by Django 3.0.2 on 2020-01-29 15:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0003_auto_20200114_1559'),
    ]

    operations = [
        migrations.RenameField(
            model_name='minutelymeasurement',
            old_name='collection_date',
            new_name='slave_collection_date',
        ),
        migrations.RenameField(
            model_name='monthlymeasurement',
            old_name='collection_date',
            new_name='slave_collection_date',
        ),
        migrations.RenameField(
            model_name='quarterlymeasurement',
            old_name='collection_date',
            new_name='slave_collection_date',
        ),
        migrations.AddField(
            model_name='minutelymeasurement',
            name='transductor_collection_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
