# Generated by Django 3.0.2 on 2020-04-02 13:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0003_auto_20200402_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlymeasurement',
            name='active_max_power_list_off_peak',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, default=None, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='monthlymeasurement',
            name='active_max_power_list_off_peak_time',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(), blank=True, default=None, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='monthlymeasurement',
            name='active_max_power_list_peak',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, default=None, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='monthlymeasurement',
            name='active_max_power_list_peak_time',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(), blank=True, default=None, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='monthlymeasurement',
            name='active_max_power_off_peak_time',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='monthlymeasurement',
            name='active_max_power_peak_time',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='monthlymeasurement',
            name='capacitive_power_off_peak_time',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='monthlymeasurement',
            name='capacitive_power_peak_time',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='monthlymeasurement',
            name='consumption_off_peak_time',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='monthlymeasurement',
            name='consumption_peak_time',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='monthlymeasurement',
            name='generated_energy_off_peak_time',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='monthlymeasurement',
            name='generated_energy_peak_time',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='monthlymeasurement',
            name='inductive_power_off_peak_time',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='monthlymeasurement',
            name='inductive_power_peak_time',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='monthlymeasurement',
            name='reactive_max_power_list_off_peak',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, default=None, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='monthlymeasurement',
            name='reactive_max_power_list_off_peak_time',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(), blank=True, default=None, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='monthlymeasurement',
            name='reactive_max_power_list_peak',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, default=None, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='monthlymeasurement',
            name='reactive_max_power_list_peak_time',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(), blank=True, default=None, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='monthlymeasurement',
            name='reactive_max_power_off_peak_time',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='monthlymeasurement',
            name='reactive_max_power_peak_time',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='quarterlymeasurement',
            name='capacitive_power_off_peak_time',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='quarterlymeasurement',
            name='capacitive_power_peak_time',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='quarterlymeasurement',
            name='consumption_off_peak_time',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='quarterlymeasurement',
            name='consumption_peak_time',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='quarterlymeasurement',
            name='generated_energy_off_peak_time',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='quarterlymeasurement',
            name='generated_energy_peak_time',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='quarterlymeasurement',
            name='inductive_power_off_peak_time',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='quarterlymeasurement',
            name='inductive_power_peak_time',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
