# Generated by Django 3.0.2 on 2020-02-03 15:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0004_auto_20200129_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlymeasurement',
            name='transductor_collection_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='quarterlymeasurement',
            name='transductor_collection_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
