# Generated by Django 3.0.14 on 2021-05-09 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0004_auto_20200402_1309'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='minutelymeasurement',
            options={'default_related_name': 'minutely_measurements'},
        ),
    ]
