# Generated by Django 2.1.5 on 2019-02-06 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0004_auto_20190129_1207'),
        ('measurement', '0004_hourmeasurement_minutemeasurement_quartermeasurement'),
    ]

    operations = [
    ]
