# Generated by Django 2.1.5 on 2019-02-13 13:57

import django.contrib.postgres.fields
import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0007_auto_20190213_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlymeasurement',
            name='active_max_power_list_off_peak_time',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=django.contrib.postgres.fields.hstore.HStoreField(), default=[{'value': '0'}], size=None),
        ),
        migrations.AlterField(
            model_name='monthlymeasurement',
            name='active_max_power_list_peak_time',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=django.contrib.postgres.fields.hstore.HStoreField(), default=[{'value': '0'}], size=None),
        ),
        migrations.AlterField(
            model_name='monthlymeasurement',
            name='reactive_max_power_list_off_peak_time',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=django.contrib.postgres.fields.hstore.HStoreField(), default=[{'value': '0'}], size=None),
        ),
        migrations.AlterField(
            model_name='monthlymeasurement',
            name='reactive_max_power_list_peak_time',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.hstore.HStoreField(), default=[{'value': '0'}], size=None),
        ),
    ]
