# Generated by Django 2.1.5 on 2019-03-14 16:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0009_auto_20190314_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minutelymeasurement',
            name='collection_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='monthlymeasurement',
            name='collection_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='quarterlymeasurement',
            name='collection_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
