# Generated by Django 2.1.5 on 2019-05-27 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0010_auto_20190314_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minutelymeasurement',
            name='transductor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurement_minutelymeasurement', to='transductor.EnergyTransductor'),
        ),
        migrations.AlterField(
            model_name='monthlymeasurement',
            name='transductor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurement_monthlymeasurement', to='transductor.EnergyTransductor'),
        ),
        migrations.AlterField(
            model_name='quarterlymeasurement',
            name='transductor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurement_quarterlymeasurement', to='transductor.EnergyTransductor'),
        ),
    ]
